//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_spotonsepia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_seller
    {
        public int visit_id { get; set; }
        public string first_name { get; set; }
        public string sel_password { get; set; }
        public string sel_image { get; set; }
        public Nullable<System.DateTime> visited_at { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> Ser_id_fk { get; set; }
        public Nullable<int> cus_id_fk { get; set; }
        public Nullable<int> inv_id_fk { get; set; }
        public Nullable<int> order_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_invoice tbl_invoice { get; set; }
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_services tbl_services { get; set; }
    }
}
