//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_spotonsepia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_services()
        {
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.tbl_order = new HashSet<tbl_order>();
            this.tbl_seller = new HashSet<tbl_seller>();
        }
    
        public int Ser_id { get; set; }
        public string Ser_name { get; set; }
        public Nullable<int> Ser_price { get; set; }
        public string Ser_desc { get; set; }
        public string Ser_image { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
        public Nullable<int> cus_id_fk { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_customer tbl_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_seller> tbl_seller { get; set; }
    }
}
